# Generated by Django 5.2.4 on 2025-07-12 20:05

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_pin', models.CharField(default='8729', max_length=4, validators=[django.core.validators.MinLengthValidator(4, 'PIN deve ter exatamente 4 dígitos'), django.core.validators.RegexValidator('^\\d{4}$', 'PIN deve conter apenas números')])),
                ('door_open_duration', models.IntegerField(default=5, help_text='Duração da abertura da porta em segundos')),
                ('max_login_attempts', models.IntegerField(default=3, help_text='Número máximo de tentativas de login')),
            ],
            options={
                'verbose_name': 'Configuração do Sistema',
                'verbose_name_plural': 'Configurações do Sistema',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('pin', models.CharField(help_text='PIN de 4 dígitos para acesso', max_length=4, validators=[django.core.validators.MinLengthValidator(4, 'PIN deve ter exatamente 4 dígitos'), django.core.validators.RegexValidator('^\\d{4}$', 'PIN deve conter apenas números')])),
                ('password', models.CharField(max_length=128)),
                ('is_active_user', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
            },
        ),
        migrations.CreateModel(
            name='AccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_time', models.DateTimeField(auto_now_add=True)),
                ('success', models.BooleanField(default=False)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='access_logs', to='api.user')),
            ],
            options={
                'verbose_name': 'Log de Acesso',
                'verbose_name_plural': 'Logs de Acesso',
                'ordering': ['-access_time'],
            },
        ),
    ]
