# Generated by Django 5.2.4 on 2025-07-13 18:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nome do dispositivo', max_length=100, unique=True)),
                ('ip_address', models.GenericIPAddressField(help_text='Endereço IP do dispositivo', unique=True)),
                ('description', models.TextField(blank=True, help_text='Descrição do dispositivo', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Dispositivo ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Dispositivo',
                'verbose_name_plural': 'Dispositivos',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=150),
        ),
        migrations.AddField(
            model_name='accesslog',
            name='device',
            field=models.ForeignKey(blank=True, help_text='Dispositivo onde ocorreu o acesso', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='access_logs', to='api.device'),
        ),
        migrations.AddField(
            model_name='systemconfig',
            name='device',
            field=models.ForeignKey(blank=True, help_text='Dispositivo da configuração', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='configs', to='api.device'),
        ),
        migrations.AddField(
            model_name='user',
            name='device',
            field=models.ForeignKey(blank=True, help_text='Dispositivo ao qual o usuário pertence', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='api.device'),
        ),
        migrations.AlterUniqueTogether(
            name='systemconfig',
            unique_together={('device',)},
        ),
        migrations.AlterUniqueTogether(
            name='user',
            unique_together={('device', 'username')},
        ),
    ]
